# Generated by Django 2.0.1 on 2018-03-27 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sovellus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='autot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('malli', models.CharField(max_length=200)),
                ('kayttovoima', models.CharField(max_length=200)),
                ('vaihteisto', models.CharField(max_length=200)),
                ('hinta', models.IntegerField()),
                ('tunniste', models.IntegerField()),
                ('moottori', models.IntegerField()),
                ('vuosimalli', models.IntegerField()),
                ('mittarilukema', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='video',
        ),
    ]
